version: "3"
services:
  n1:
    container_name: node1
    build: .
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
    restart: on-failure
    networks:
      test:
        ipv4_address: 173.0.0.2
    volumes:
      - ./nodes/node_01:/nodes/node1  

  n2:
    container_name: node2
    build: .
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
    restart: on-failure
    networks:
      test:
        ipv4_address: 173.0.0.3
    volumes:
      - ./nodes/node_02:/nodes/node1  

networks:
  test:
    driver: bridge
    ipam:
     config:
        - subnet: 173.0.0.0/16








  